export const FETCH_ARTICLES_START = "FETCH_ARTICLES_START";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";

export const FETCH_ONE_ARTICLE_START = "FETCH_ONE_ARTICLE_START";
export const FETCH_ONE_ARTICLE_SUCCESS = "FETCH_ONE_ARTICLE_SUCCESS";
export const FETCH_ONE_ARTICLE_FAILURE = "FETCH_ONE_ARTICLE_FAILURE";

export const DELETE_ARTICLE_START = "DELETE_ARTICLE_START";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILURE = "DELETE_ARTICLE_FAILURE";

export const CLEAR_ARTICLE = "CLEAR_ARTICLE";
export const CLEAR_ALL_ARTICLES = "CLEAR_ALL_ARTICLES";
export const CLEAR_ERRORS_AND_LINK = "CLEAR_ERRORS_AND_LINK";

export const UPLOAD_IMAGE_START = "UPLOAD_IMAGE_START";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";

export const CREATE_ARTICLE_START = "CREATE_ARTICLE_START";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAILURE = "CREATE_ARTICLE_FAILURE";

export const UPDATE_ARTICLE_START = "UPDATE_ARTICLE_START";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILURE = "UPDATE_ARTICLE_FAILURE";

export const SEARCH_ARTICLES_START = "SEARCH_ARTICLES_START";
export const SEARCH_ARTICLES_SUCCESS = "SEARCH_ARTICLES_SUCCESS";
export const SEARCH_ARTICLES_FAILURE = "SEARCH_ARTICLES_FAILURE";

export const GET_TECHNOLOGIES_SUCCESS = "GET_TECHNOLOGIES_SUCCESS";
